config/routes.rb
ProtoCRM3::Application.routes.draw do

match "web" => "prospectos#webtest", as: :web
  resources :searches

  resources :efectividads

  resources :duracion_en_textos

  resources :configuraciones

  resources :dictamen_psicometria

  resources :dictamen_paas

  resources :report_directions

  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  resources :comments do
    resources :comments
  end

  resources :articles do
    resources :comments
  end

  


  resources :rpms

  resources :histories

  resources :status_ref_pago_inscs

  resources :status_del_examinado_psicos

  resources :status_del_examinado_entrevista


  resources :modalidads

  resources :role_permisions

  resources :roles

  resources :metas_globales

  resources :contactos

  resources :equipo_de_alto_rendimientos

  resources :nacional_de_aperturas

  resources :division_territorials

  resources :colegiaturas

  resources :oferta_educativas

  resources :mi_plan_estrategico_de_promocion_peps

  resources :achievments

  resources :meta

  resources :reportlines

  resources :grupos

  resources :tweets

  resources :subsedes

  resources :events

  resources :posts

  resources :campana_socials

  resources :authentications

  resources :imports

  resources :reportsortbies

  resources :reportparams

  resources :reports

  resources :statics

  resources :correos

  resources :live_reports

  resources :status_del_pago_de_la_inscripcions

  resources :status_de_la_inscripcions

  resources :status_del_admitidos

  resources :status_de_la_notificacions

  resources :status_de_admisions

  resources :status_del_examinado_paas

  resources :status_del_tramite_de_becas

  resources :status_de_pago_eses

  resources :status_de_eses

  resources :tipo_de_admisions

  resources :status_de_pago_de_examen_de_admisions

  resources :status_de_la_accion_1s

  resources :status_de_interes_de_prospecto_validados

  resources :periodo_para_ingresars

  resources :turnos

  resources :nivels

  resources :programa_de_interes

  resources :municipio_de_la_preparatoria_o_universidad_de_origens

  resources :employmentships

  resources :dashboards

  resources :llamadas

  resources :preparatoria_o_universidad_de_origens

  resources :memos

  resources :attachments

  resources :tareas

  resources :barra_favoritos

  resources :favoritos

  resources :ultimo_grado_de_estudios

  resources :nacionalidads

  resources :pregunta

  resources :casos

  resources :equipo_promocions

  resources :programas

  resources :territorios

  resources :plan_de_venta

  resources :finalidad_cultivos

  resources :comentarios_estrategia

  resources :estrategia_promocionals

  resources :mercado_meta


  resources :purges
  resources :inscritos
  resources :admitidos
  resources :examinados
  resources :solicitantes
  resources :prospectos

resources :prospectos, only: :index do
    match 'advanced_search' => 'prospectos#advanced_search',
          on: :collection, via: [:get, :post], as: :advanced_search
  end

  resources :sedes

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks",:sessions => "sessions" }
  resources :users
  
 devise_for :prospectos, :skip => [:webtest] 
  root :to => "homes#force_redirect"
 
  
  match "/solicitantes/:id/convertir_solicitante" => "solicitantes#convertir_solicitante", as: :convertir_solicitante
  match "/examinados/:id/convertir_examinado" => "examinados#convertir_examinado", as: :convertir_examinado
  match "/admitidos/:id/convertir_admitido" => "admitidos#convertir_admitido", as: :convertir_admitido
  match "/prospectos/:id/validar" => "prospectos#validar", as: :validar,:validado=>false
  match "/prospectos/:id/convertir" => "prospectos#convertir", as: :convertir, :validado=>true
  match "/multiexport" => "prospectos#multiexport"
  match "/purgeprospectos" => "prospectos#purgeprospectos"
  match "/borrarprospectosinvalidos" => "prospectos#borrarprospectosinvalidos"

  match "/multiexports" => "prospectos#multiexports"
  match "/multiexporta" => "prospectos#multiexporta"
  match "/multiexporte" => "prospectos#multiexporte"
  match "/multiexporti" => "prospectos#multiexporti"
  match "/mostrarmultiple" => "prospectos#mostrarmultiple"
  match "/cambiarmultiple" => "prospectos#cambiarmultiple"
  match "/webtest" => "prospectos#webtest"

  match "/inscritos/:id/convertir_en_admitido" => "inscritos#convertir_en_admitido", as: :convertir_en_admitido





  match 'saved_search_add' => "searches#saved_search", as: :saved_search
  match 'redir_to_saved' => "searches#redir_to_saved", as: :redir_to_saved
  
  

  
  match "/purge_admitidos"=>"purges#purge_admitidos",as: :purge_admitidos
  match "/purge_examinados"=>"purges#purge_examinados",as: :purge_examinados
  match "/purge_inscritos"=>"purges#purge_inscritos",as: :purge_inscritos
  match "/purge_prospectos"=>"purges#purge_prospectos",as: :purge_prospectos
  match "/purge_sedes"=>"purges#purge_sedes",as: :purge_sedes
  match "/purge_solicitantes"=>"purges#purge_solicitantes",as: :purge_solicitantes
  match "/purge_users"=>"purges#purge_users",as: :purge_users
  match "/purge_all"=>"purges#purge_all",as: :purge_all
  match "/purge_test"=>"purges#purge_test",as: :purge_test

  match "/home"=>"homes#index",as: :home

  
  match "/empleados" => "dashboards#empleados", as: :empleados
  match "/rcircular" => "dashboards#rcircular", as: :rcircular
  match "/rsemanal" => "dashboards#rsemanal", as: :rcircular

  match "/miscorreos" => "statics#miscorreos", as: :miscorreos
  match "/correosenviados" => "statics#correosenviados", as: :correosenviados



  match "/enviandocorreos" => "correos#enviandocorreos", as: :enviandocorreos
  match "/send_correo_individually" => "correos#send_correo_individually", as: :send_correo_individually
  

  match "/campanasenviadas" => "statics#campanasenviadas", as: :campanasenviadas

  match "/prospectos/:id/printview" => "prospectos#printview", as: :printview
  match "/prospectos/:id/printviewpdf" => "prospectos#printviewpdf", as: :printviewpdf

  match "/achievments/:id/printview" => "achievments#printview", as: :printview

  match "/admitidos/:id/printview" => "admitidos#printview", as: :printview
  match "/admitidos/:id/printviewpdf" => "admitidos#printviewpdf", as: :printviewpdf

  match "/reports/:id/printview" => "reports#printview", as: :printview
  match "/solicitantes/:id/printview" => "solicitantes#printview", as: :printview
  match "/solicitantes/:id/printviewpdf" => "solicitantes#printviewpdf", as: :printviewpdf

  match "/examinados/:id/printview" => "examinados#printview", as: :printview
  match "/examinados/:id/printviewpdf" => "examinados#printviewpdf", as: :printviewpdf

  match "/inscritos/:id/printview" => "inscritos#printview", as: :printview
  match "/inscritos/:id/printviewpdf" => "inscritos#printviewpdf", as: :printviewpdf

  match "/admitidos/:id/printview" => "admitidos#printview", as: :printview
  match "/inscritos/:id/printview" => "inscritos#printview", as: :printview
  match "/rpms/:id/printview" => "rpms#printview", as: :printview


  match "/programas/:id/borrar" => "programas#borrar", as: :borrar
  match "/programas/:id/masschange" => "programas#masschange", as: :masschange



  match "/prospectos/:id/resumen"=>"prospectos#resumen", as: :resumen
  
  match "/reports/:id/imprimir" => "reports#imprimir", as: :imprimir
  match "/rpms/:id/imprimir" => "rpms#imprimir", as: :imprimir_rpm
  match "/imports/:id/uploadcsv" => "imports#uploadcsv", as: :uploadcsv

  
  match "/correos/:id/send_correo" => "correos#send_correo", as: :send_correo
  match "/correos/:id/send_correo_individually" => "correos#send_correo_individually", as: :send_correo_individually
  match "/tweets/:id/send_tweet" => "tweets#send_tweet", as: :send_tweet

  match '/auth/:provider/callback' => 'authentications#create'
  match '/auth/google_apps/callback' => 'authentications#create'
  match '/opciones' => 'dashboards#opciones', as: :opciones
  match '/mispendientes' => 'dashboards#mispendientes', as: :mispendientes
  match '/stweet' => 'homes#stweet', as: :stweet

  match '/home2' => 'homes#home2', as: :home2
match "/posts/:id/send_post" => "posts#send_post", as: :send_post

  match "versions/:id/revert" => "versions#revert", :as => "revert_version"



match "/llamadas/:id/convertir_llamada" => "llamadas#convertir_llamada", as: :convertir_llamada
match "/memos/:id/convertir_memo" => "memos#convertir_memo", as: :convertir_memo
match "/tareas/:id/convertir_tarea" => "tareas#convertir_tarea", as: :convertir_tarea












end

app/models/rpm.rb
class Rpm < ActiveRecord::Base
	serialize :prospectos
	serialize :usuarios
	serialize :sedes
	serialize :subsedes
	serialize :programas
	serialize :campanas

	serialize :sede_id
	serialize :subsede_id
	serialize :nivel_id

	serialize :nacionalidad_id
	serialize :ultimo_grado_de_estudio_id
	serialize :preparatoria_o_universidad_de_origen_id
	serialize :municipio_de_la_preparatoria_o_universidad_de_origen_id
	serialize :periodo_para_ingresar_id
	serialize :status_de_admision_id
	serialize :status_de_ese_id
	serialize :status_de_interes_de_prospecto_validado_id
	serialize :status_de_la_inscripcion_id
	serialize :status_de_la_notificacion_id
	serialize :status_de_pago_de_examen_de_admision_id
	serialize :status_de_pago_de_ese_id
	serialize :status_del_admitido_id
	serialize :status_del_examinado_paa_id
	serialize :status_del_pago_de_la_inscripcion_id
	serialize :status_del_tramite_de_beca_id
	serialize :tipo_de_admision_id
	serialize :turno_id
	serialize :modalidad_id
	serialize :grupo_id
	serialize :status_ref_pago_inscs_id
	serialize :status_del_examinado_psico_id
	serialize :status_del_examinado_entrevistum_id 	

	serialize :medio_de_contactos_id

	serialize :columnas
	serialize :columnas_seleccionadas

	validates_presence_of :rango_inicio
	validates_presence_of :rango_fin
	
end

app/controllers/rpms_controller.rb
class RpmsController < ApplicationController
before_filter :authenticate_user!

  # GET /rpms
  # GET /rpms.json
  def index
  rol = Role.where(:id=>current_user.role).first

   if rol.nombre == "DN" or rol.nombre == "ACRM"
    @rpms = Rpm.all
  else
    @rpms = Rpm.where(:created_by=>current_user)
  end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @rpms }
    end
  end

  # GET /rpms/1
  # GET /rpms/1.json
  def show
    @rpm = Rpm.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @rpm }
    end
  end

  # GET /rpms/new
  # GET /rpms/new.json
  def new
    @rpm = Rpm.new
    @rpm.created_by = current_user.id

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @rpm }
    end
  end

  # GET /rpms/1/edit
  def edit
    @rpm = Rpm.find(params[:id])
  end

  # POST /rpms
  # POST /rpms.json
  def create
    @rpm = Rpm.new(params[:rpm])

    respond_to do |format|
      if @rpm.save
        format.html { redirect_to imprimir_rpm_path(@rpm), notice: 'Rpm was successfully created.' }
        format.json { render json: @rpm, status: :created, location: @rpm }
      else
        format.html { render action: "new" }
        format.json { render json: @rpm.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /rpms/1
  # PUT /rpms/1.json
  def update
    @rpm = Rpm.find(params[:id])
    @rpm.save
    respond_to do |format|
      if @rpm.update_attributes(params[:rpm])
        format.html { redirect_to imprimir_rpm_path(@rpm) }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @rpm.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rpms/1
  # DELETE /rpms/1.json
  def destroy



rol = Role.where(:id=>current_user.role).first
        if rol.nombre == "ACRM"
  
    
    @rpm = Rpm.find(params[:id])
    @rpm.destroy
else
  flash[:error] ='No tienes permiso para realizar esta accion'

end

    respond_to do |format|
      format.html { redirect_to rpms_url }
      format.json { head :ok }
    end
  end

  def imprimir
  end

  def printview
    @rpm = Rpm.find(params[:id])
    render :layout => false  
  end
end

app/helpers/rpms_helper.rb
module RpmsHelper
end

app/views/rpms/_resumen.html.erb
						<%
					      #find prospecto first
					      @prospecto = Prospecto.where(:id=>prospectoid).first
					      if @prospecto!=nil
					        @tareas1 = Tarea.where(:model_name=>"prospectos",:model_id=>@prospecto.id)
					        @memos1 = Memo.where(:model_name=>"prospectos",:model_id=>@prospecto.id)
					        @attachments1 = Attachment.where(:model_name=>"prospectos",:model_id=>@prospecto.id)
					        @llamadas1 = Llamada.where(:model_name=>"prospectos",:model_id=>@prospecto.id)
					        @correos1 = Correo.where(:model_name=>"prospectos",:model_id=>@prospecto.id)
					        if @prospecto.solicitante_id != nil
					          @solicitante = Solicitante.find(@prospecto.solicitante_id)
					          @llamadas2 = Llamada.where(:model_name=>"solicitantes",:model_id=>@solicitante.id)
					          @correos2 = Correo.where(:model_name=>"solicitantes",:model_id=>@solicitante.id)
					          @attachments2 = Attachment.where(:model_name=>"solicitantes",:model_id=>@solicitante.id)
					          @memos2 = Memo.where(:model_name=>"solicitantes",:model_id=>@solicitante.id)
					          @tareas2 = Tarea.where(:model_name=>"solicitantes",:model_id=>@solicitante.id)
					          #check if he has a examinado
					          if @solicitante.examinado_id !=nil
					            @examinado = Examinado.find(@solicitante.examinado_id)
					            @tareas3 = Tarea.where(:model_name=>"examinados",:model_id=>@examinado.id)
					            @memos3 = Memo.where(:model_name=>"examinados",:model_id=>@examinado.id)
					            @correos3 = Correo.where(:model_name=>"examinados",:model_id=>@examinado.id)
					            @attachments3 = Attachment.where(:model_name=>"examinados",:model_id=>@examinado.id)
					            @llamadas3 = Llamada.where(:model_name=>"examinados",:model_id=>@examinado.id)
					            
					            #check if he has an admitido
					            if @examinado.admitido_id !=nil
					              @admitido = Admitido.find(@examinado.admitido_id)
					              @tareas4 = Tarea.where(:model_name=>"admitidos",:model_id=>@admitido.id)
					              @correos4 = Correo.where(:model_name=>"admitidos",:model_id=>@admitido.id)
					              @attachments4 = Attachment.where(:model_name=>"admitidos",:model_id=>@admitido.id)
					              @llamadas4 = Llamada.where(:model_name=>"admitidos",:model_id=>@admitido.id)
					              @memos4 = Memo.where(:model_name=>"admitidos",:model_id=>@admitido.id)
					              
					              #check if he has an inscrito
					              if @admitido.inscrito_id !=nil
					                @inscrito = Inscrito.find(@admitido.inscrito_id)
					                @tareas5 = Tarea.where(:model_name=>"inscritos",:model_id=>@inscrito.id)
					                @memos5 = Memo.where(:model_name=>"inscritos",:model_id=>@inscrito.id)
					                @correos5 = Correo.where(:model_name=>"inscritos",:model_id=>@inscrito.id)
					                @attachments5 = Attachment.where(:model_name=>"inscritos",:model_id=>@inscrito.id)
					                @llamadas5 = Llamada.where(:model_name=>"inscritos",:model_id=>@inscrito.id)
					                
					              end
					            end
					          end
					        end
					      end
						%>	
<%enabled=false%>
<%if @inscrito !=nil%>
  <%enabled =true%>
  <%= render :partial => "inscritoNav"%>
  <%=render :partial=>"shared/show_inscritos", :locals=>{:f=>@inscrito,:prospectoid=>@prospecto.id,:isactive=>" in active "}%>
<!-- END111111111111111111111111111111111111111-->
<%elsif @admitido != nil && enabled==false%>
<%enabled =true%>
<%= render :partial => "admitidoNav"%>
<%=render :partial=>"shared/show_admitidos", :locals=>{:f=>@admitido,:prospectoid=>@prospecto.id,:isactive=>" in active "}%>
<%elsif @examinado != nil && enabled==false%>
<%enabled =true%>
<%= render :partial => "examinadoNav"%>
<%=render :partial=>"shared/show_examinados", :locals=>{:f=>@examinado,:prospectoid=>@prospecto.id,:isactive=>" in active "}%>
<%elsif @solicitante!= nil && enabled==false%>
<%enabled =true%>
<%= render :partial => "solicitanteNav"%>
<%=render :partial=>"shared/show_solicitantes", :locals=>{:f=>@solicitante,:prospectoid=>@prospecto.id,:isactive=>" in active "}%>
<%elsif @prospecto != nil && enabled==false%>
<%enabled =true%>
<%= render :partial => "prospectoNav"%>
<%=render :partial=>"shared/show_prospectos", :locals=>{:f=>@prospecto,:prospectoid=>@prospecto.id,:isactive=>" in active "}%>
<%end%>


<div class="tabbable"> <!-- Only required for left/right tabs -->
  <ul class="nav nav-tabs">
    <li class="active"><a href="#tareas" data-toggle="tab">Tareas</a></li>
    <li><a href="#llamadas" data-toggle="tab">Llamadas</a></li>
    <li><a href="#memos" data-toggle="tab">Memos</a></li>
    <li><a href="#correos" data-toggle="tab">Correos</a></li>
    <li><a href="#attachments" data-toggle="tab">Adjuntos</a></li>
  </ul>
  <div class="tab-content">
    <div class="tab-pane active" id="tareas">
		<%
		  #render a partial for any tareas
		  tareas =[@tareas1,@tareas2,@tareas3,@tareas4,@tareas5].flatten.compact.sort
		  %>

		    <div class="well">
		      <h3>Tareas</h3>
		       <table class="table table-striped table-bordered table-condensed">
		        <thead>
		          <tr>
		            <th>ID</th>
		            <th>Nombre</th>
		            <th>Creado en </th>
		            <th>Actions</th>
		          </tr>
		        </thead>
		        <tbody>
		          <%if tareas[0] != nil%>
		            <% tareas.each do |tarea| %>
		              <tr>
		                <td><%= link_to tarea.id, tarea_path(tarea) %></td>
		                <td><%= link_to tarea.nombre, tarea_path(tarea) %></td>
		                <td><%= link_to tarea.created_at, tarea_path(tarea) %></td>
		                <td>
		                  <%= link_to 'Edit', edit_tarea_path(tarea), :class => 'btn btn-mini' %>
		                  <%= link_to 'Destroy', tarea_path(tarea), :method => :delete, :confirm => 'Are you sure?', :class => 'btn btn-mini btn-danger' %>
		                </td>
		              </tr>
		            <% end %>
		          <%end%>
		        </tbody>
		      </table>
		      <%= link_to 'Nueva Tarea', new_tarea_path(:model_name=>request.path_parameters[:controller],:model_id=>@prospecto.id), :class => 'btn btn-primary' %>
		    </div>
    </div>
    <div class="tab-pane" id="llamadas">
		<%
		  #render a partial for any llamadas
		  llamadas =[@llamadas1,@llamadas2,@llamadas3,@llamadas4,@llamadas5].flatten.compact.sort
		  %>

		    <div class="well">
		      <h3>Llamadas</h3>
		       <table class="table table-striped table-bordered table-condensed">
		        <thead>
		          <tr>
		            <th>ID</th>
		            <th>Asunto</th>
		            <th>Creado en </th>
		            <th>Actions</th>
		          </tr>
		        </thead>
		        <tbody>
		          <%if llamadas[0] != nil%>
		            <% llamadas.each do |llamada| %>
		              <tr>
		                <td><%= link_to llamada.id, llamada_path(llamada) %></td>
		                <td><%= link_to llamada.asunto, llamada_path(llamada) %></td>
		                <td><%= link_to llamada.created_at, llamada_path(llamada) %></td>
		                <td>
		                  <%= link_to 'Edit', edit_llamada_path(llamada), :class => 'btn btn-mini' %>
		                  <%= link_to 'Destroy', llamada_path(llamada), :method => :delete, :confirm => 'Are you sure?', :class => 'btn btn-mini btn-danger' %>
		                </td>
		              </tr>
		            <% end %>
		          <%end%>
		        </tbody>
		      </table>
		      <%= link_to 'Nuevo Llamada', new_llamada_path(:model_name=>request.path_parameters[:controller],:model_id=>@prospecto.id), :class => 'btn btn-primary' %>
		    </div>
    </div>
    <div class="tab-pane" id="memos">
		 <%
		  #render a partial for any memos
		  memos =[@memos1,@memos2,@memos3,@memos4,@memos5].flatten.compact.sort
		  %>

		    <div class="well">
		      <h3>Notas</h3>
		       <table class="table table-striped table-bordered table-condensed">
		        <thead>
		          <tr>
		            <th>ID</th>
		            <th>Nombre</th>
		            <th>Creado en </th>
		            <th>Actions</th>
		          </tr>
		        </thead>
		        <tbody>
		          <%if memos[0] != nil%>
		          <% memos.each do |memo| %>
		            <tr>
		              <td><%= link_to memo.id, memo_path(memo) %></td>
		              <td><%= link_to memo.nombre, memo_path(memo) %></td>
		              <td><%= link_to memo.created_at, memo_path(memo) %></td>
		              <td>
		                <%= link_to 'Edit', edit_memo_path(memo), :class => 'btn btn-mini' %>
		                <%= link_to 'Destroy', memo_path(memo), :method => :delete, :confirm => 'Are you sure?', :class => 'btn btn-mini btn-danger' %>
		              </td>
		            </tr>
		          <% end %>
		          <%end%>
		        </tbody>
		      </table>
		      <%= link_to 'Nueva Nota', new_memo_path(:model_name=>request.path_parameters[:controller],:model_id=>@prospecto.id), :class => 'btn btn-primary' %>
		    </div>  
    </div>
    <div class="tab-pane" id="correos">
		 <%
		  #render a partial for any attachments
		  correos =[@correos1,@correos2,@correos3,@correos4,@correos5].flatten.compact.sort
		  %>

		    <div class="well">
		      <h3>Correos</h3>
		       <table class="table table-striped table-bordered table-condensed">
		        <thead>
		          <tr>
		            <th>ID</th>
		            <th>Nombre</th>
		            <th>Creado en </th>
		            <th>Actions</th>
		          </tr>
		        </thead>
		        <tbody>
		          <%if correos[0] != nil%>
		          <% correos.each do |correo| %>
		            <tr>
		              <td><%= link_to correo.id, correo_path(correo) %></td>
		              <td><%= link_to correo.nombredelmail, correo_path(correo) %></td>
		              <td><%= link_to correo.created_at, correo_path(correo) %></td>
		              <td>
		                <%= link_to 'Edit', edit_correo_path(correo), :class => 'btn btn-mini' %>
		                <%= link_to 'Destroy', correo_path(correo), :method => :delete, :confirm => 'Are you sure?', :class => 'btn btn-mini btn-danger' %>
		              </td>
		            </tr>
		          <% end %>
		          <%end%>
		        </tbody>
		      </table>
		      <%= link_to 'Nuevo Correo', new_correo_path(:model_name=>request.path_parameters[:controller],:model_id=>@prospecto.id), :class => 'btn btn-primary' %>
		    </div>  
    </div>
    <div class="tab-pane" id="attachments">
		<%
		  #render a partial for any attachments
		  attachments =[@attachments1,@attachments2,@attachments3,@attachments4,@attachments5].flatten.compact.sort
		  %>
		 
		    <div class="well">
		      <h3>Archivos Adjuntos</h3>
		       <table class="table table-striped table-bordered table-condensed">
		        <thead>
		          <tr>
		            <th>ID</th>
		            <th>Nombre</th>
		            <th>Creado en </th>
		            <th>Actions</th>
		          </tr>
		        </thead>
		        <tbody>
		          <%if attachments[0] != nil%>
		          <% attachments.each do |attachment| %>
		            <tr>
		              <td><%= link_to attachment.id, attachment_path(attachment) %></td>
		              <td><%= link_to attachment.name, attachment_path(attachment) rescue nil%></td>
		              <td><%= link_to attachment.created_at, attachment_path(attachment) %></td>
		              <td>
		                <%= link_to 'Edit', edit_attachment_path(attachment), :class => 'btn btn-mini' %>
		                <%= link_to 'Destroy', attachment_path(attachment), :method => :delete, :confirm => 'Are you sure?', :class => 'btn btn-mini btn-danger' %>
		              </td>
		            </tr>
		          <% end %>
		          <%end%>
		        </tbody>
		      </table>
		      <%= link_to 'Nuevo Adjunto', new_attachment_path(:model_name=>request.path_parameters[:controller],:model_id=>@prospecto.id), :class => 'btn btn-primary' %>
		    </div>  
    </div>            
  </div>
</div>

app/views/rpms/edit.html.erb
<h1>Reportes simples</h1>
<%= render :partial => 'form' %>

app/views/rpms/index.html.erb
<%- model_class = Rpm.new.class -%>
<h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
<table class="table table-striped table-bordered table-condensed table-bordered table-condensed">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:nombre) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @rpms.each do |rpm| %>
      <tr>
        <td><%= link_to rpm.id, edit_rpm_path(rpm) %></td>
        <td><%= link_to rpm.nombre, edit_rpm_path(rpm) %></td>
        <td><%= link_to rpm.created_at , edit_rpm_path(rpm)%></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_rpm_path(rpm), :class => 'btn btn-info btn-mini' %>
          <%= link_to "Imprimir",
                      imprimir_rpm_path(rpm), :class => 'btn btn-mini' %>
          <%= link_to "Exportar",
                      imprimir_rpm_path(rpm,format: :xls),:format=>"xls", :class => 'btn btn-success btn-mini' %>                                            
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      contacto_path(rpm),
                      :method => :delete,
                      :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')),
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_rpm_path,
            :class => 'btn btn-primary' %>

app/views/rpms/new.html.erb
<%= render :partial => 'form' %>