config/routes.rb
ProtoCRM3::Application.routes.draw do

match "web" => "prospectos#webtest", as: :web
  resources :searches

  resources :efectividads

  resources :duracion_en_textos

  resources :configuraciones

  resources :dictamen_psicometria

  resources :dictamen_paas

  resources :report_directions

  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  resources :comments do
    resources :comments
  end

  resources :articles do
    resources :comments
  end

  


  resources :rpms

  resources :histories

  resources :status_ref_pago_inscs

  resources :status_del_examinado_psicos

  resources :status_del_examinado_entrevista


  resources :modalidads

  resources :role_permisions

  resources :roles

  resources :metas_globales

  resources :contactos

  resources :equipo_de_alto_rendimientos

  resources :nacional_de_aperturas

  resources :division_territorials

  resources :colegiaturas

  resources :oferta_educativas

  resources :mi_plan_estrategico_de_promocion_peps

  resources :achievments

  resources :meta

  resources :reportlines

  resources :grupos

  resources :tweets

  resources :subsedes

  resources :events

  resources :posts

  resources :campana_socials

  resources :authentications

  resources :imports

  resources :reportsortbies

  resources :reportparams

  resources :reports

  resources :statics

  resources :correos

  resources :live_reports

  resources :status_del_pago_de_la_inscripcions

  resources :status_de_la_inscripcions

  resources :status_del_admitidos

  resources :status_de_la_notificacions

  resources :status_de_admisions

  resources :status_del_examinado_paas

  resources :status_del_tramite_de_becas

  resources :status_de_pago_eses

  resources :status_de_eses

  resources :tipo_de_admisions

  resources :status_de_pago_de_examen_de_admisions

  resources :status_de_la_accion_1s

  resources :status_de_interes_de_prospecto_validados

  resources :periodo_para_ingresars

  resources :turnos

  resources :nivels

  resources :programa_de_interes

  resources :municipio_de_la_preparatoria_o_universidad_de_origens

  resources :employmentships

  resources :dashboards

  resources :llamadas

  resources :preparatoria_o_universidad_de_origens

  resources :memos

  resources :attachments

  resources :tareas

  resources :barra_favoritos

  resources :favoritos

  resources :ultimo_grado_de_estudios

  resources :nacionalidads

  resources :pregunta

  resources :casos

  resources :equipo_promocions

  resources :programas

  resources :territorios

  resources :plan_de_venta

  resources :finalidad_cultivos

  resources :comentarios_estrategia

  resources :estrategia_promocionals

  resources :mercado_meta


  resources :purges
  resources :inscritos
  resources :admitidos
  resources :examinados
  resources :solicitantes
  resources :prospectos

resources :prospectos, only: :index do
    match 'advanced_search' => 'prospectos#advanced_search',
          on: :collection, via: [:get, :post], as: :advanced_search
  end

  resources :sedes

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks",:sessions => "sessions" }
  resources :users
  
 devise_for :prospectos, :skip => [:webtest] 
  root :to => "homes#force_redirect"
 
  
  match "/solicitantes/:id/convertir_solicitante" => "solicitantes#convertir_solicitante", as: :convertir_solicitante
  match "/examinados/:id/convertir_examinado" => "examinados#convertir_examinado", as: :convertir_examinado
  match "/admitidos/:id/convertir_admitido" => "admitidos#convertir_admitido", as: :convertir_admitido
  match "/prospectos/:id/validar" => "prospectos#validar", as: :validar,:validado=>false
  match "/prospectos/:id/convertir" => "prospectos#convertir", as: :convertir, :validado=>true
  match "/multiexport" => "prospectos#multiexport"
  match "/purgeprospectos" => "prospectos#purgeprospectos"
  match "/borrarprospectosinvalidos" => "prospectos#borrarprospectosinvalidos"

  match "/multiexports" => "prospectos#multiexports"
  match "/multiexporta" => "prospectos#multiexporta"
  match "/multiexporte" => "prospectos#multiexporte"
  match "/multiexporti" => "prospectos#multiexporti"
  match "/mostrarmultiple" => "prospectos#mostrarmultiple"
  match "/cambiarmultiple" => "prospectos#cambiarmultiple"
  match "/webtest" => "prospectos#webtest"

  match "/inscritos/:id/convertir_en_admitido" => "inscritos#convertir_en_admitido", as: :convertir_en_admitido





  match 'saved_search_add' => "searches#saved_search", as: :saved_search
  match 'redir_to_saved' => "searches#redir_to_saved", as: :redir_to_saved
  
  

  
  match "/purge_admitidos"=>"purges#purge_admitidos",as: :purge_admitidos
  match "/purge_examinados"=>"purges#purge_examinados",as: :purge_examinados
  match "/purge_inscritos"=>"purges#purge_inscritos",as: :purge_inscritos
  match "/purge_prospectos"=>"purges#purge_prospectos",as: :purge_prospectos
  match "/purge_sedes"=>"purges#purge_sedes",as: :purge_sedes
  match "/purge_solicitantes"=>"purges#purge_solicitantes",as: :purge_solicitantes
  match "/purge_users"=>"purges#purge_users",as: :purge_users
  match "/purge_all"=>"purges#purge_all",as: :purge_all
  match "/purge_test"=>"purges#purge_test",as: :purge_test

  match "/home"=>"homes#index",as: :home

  
  match "/empleados" => "dashboards#empleados", as: :empleados
  match "/rcircular" => "dashboards#rcircular", as: :rcircular
  match "/rsemanal" => "dashboards#rsemanal", as: :rcircular

  match "/miscorreos" => "statics#miscorreos", as: :miscorreos
  match "/correosenviados" => "statics#correosenviados", as: :correosenviados



  match "/enviandocorreos" => "correos#enviandocorreos", as: :enviandocorreos
  match "/send_correo_individually" => "correos#send_correo_individually", as: :send_correo_individually
  

  match "/campanasenviadas" => "statics#campanasenviadas", as: :campanasenviadas

  match "/prospectos/:id/printview" => "prospectos#printview", as: :printview
  match "/prospectos/:id/printviewpdf" => "prospectos#printviewpdf", as: :printviewpdf

  match "/achievments/:id/printview" => "achievments#printview", as: :printview

  match "/admitidos/:id/printview" => "admitidos#printview", as: :printview
  match "/admitidos/:id/printviewpdf" => "admitidos#printviewpdf", as: :printviewpdf

  match "/reports/:id/printview" => "reports#printview", as: :printview
  match "/solicitantes/:id/printview" => "solicitantes#printview", as: :printview
  match "/solicitantes/:id/printviewpdf" => "solicitantes#printviewpdf", as: :printviewpdf

  match "/examinados/:id/printview" => "examinados#printview", as: :printview
  match "/examinados/:id/printviewpdf" => "examinados#printviewpdf", as: :printviewpdf

  match "/inscritos/:id/printview" => "inscritos#printview", as: :printview
  match "/inscritos/:id/printviewpdf" => "inscritos#printviewpdf", as: :printviewpdf

  match "/admitidos/:id/printview" => "admitidos#printview", as: :printview
  match "/inscritos/:id/printview" => "inscritos#printview", as: :printview
  match "/rpms/:id/printview" => "rpms#printview", as: :printview


  match "/programas/:id/borrar" => "programas#borrar", as: :borrar
  match "/programas/:id/masschange" => "programas#masschange", as: :masschange



  match "/prospectos/:id/resumen"=>"prospectos#resumen", as: :resumen
  
  match "/reports/:id/imprimir" => "reports#imprimir", as: :imprimir
  match "/rpms/:id/imprimir" => "rpms#imprimir", as: :imprimir_rpm
  match "/imports/:id/uploadcsv" => "imports#uploadcsv", as: :uploadcsv

  
  match "/correos/:id/send_correo" => "correos#send_correo", as: :send_correo
  match "/correos/:id/send_correo_individually" => "correos#send_correo_individually", as: :send_correo_individually
  match "/tweets/:id/send_tweet" => "tweets#send_tweet", as: :send_tweet

  match '/auth/:provider/callback' => 'authentications#create'
  match '/auth/google_apps/callback' => 'authentications#create'
  match '/opciones' => 'dashboards#opciones', as: :opciones
  match '/mispendientes' => 'dashboards#mispendientes', as: :mispendientes
  match '/stweet' => 'homes#stweet', as: :stweet

  match '/home2' => 'homes#home2', as: :home2
match "/posts/:id/send_post" => "posts#send_post", as: :send_post

  match "versions/:id/revert" => "versions#revert", :as => "revert_version"



match "/llamadas/:id/convertir_llamada" => "llamadas#convertir_llamada", as: :convertir_llamada
match "/memos/:id/convertir_memo" => "memos#convertir_memo", as: :convertir_memo
match "/tareas/:id/convertir_tarea" => "tareas#convertir_tarea", as: :convertir_tarea












end

app/models/caso.rb
class Caso < ActiveRecord::Base
	belongs_to :programa
end

app/controllers/casos_controller.rb
class CasosController < ApplicationController
  before_filter :authenticate_user!  
  
  # GET /casos
  # GET /casos.json
  def index
    @casos = Caso.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @casos }
    end
  end

  # GET /casos/1
  # GET /casos/1.json
  def show
    @caso = Caso.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @caso }
    end
  end

  # GET /casos/new
  # GET /casos/new.json
  def new
    @caso = Caso.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @caso }
    end
  end

  # GET /casos/1/edit
  def edit
    @caso = Caso.find(params[:id])
  end

  # POST /casos
  # POST /casos.json
  def create
    @caso = Caso.new(params[:caso])

    respond_to do |format|
      if @caso.save
        format.html { redirect_to @caso, notice: 'Caso was successfully created.' }
        format.json { render json: @caso, status: :created, location: @caso }
      else
        format.html { render action: "new" }
        format.json { render json: @caso.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /casos/1
  # PUT /casos/1.json
  def update
    @caso = Caso.find(params[:id])

    respond_to do |format|
      if @caso.update_attributes(params[:caso])
        format.html { redirect_to @caso, notice: 'Caso was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @caso.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /casos/1
  # DELETE /casos/1.json
  def destroy
rol = Role.where(:id=>current_user.role).first


        if rol.nombre == "ACRM"


    @caso = Caso.find(params[:id])
    @caso.destroy

else
  flash[:error] ='No tienes permiso para realizar esta accion'

end
    
    respond_to do |format|
      format.html { redirect_to casos_url }
      format.json { head :ok }
    end
  end
end

app/helpers/casos_helper.rb
module CasosHelper
end

app/views/casos/_form.html.erb
<%= simple_form_for @caso, :html => { :class => 'form-horizontal' } do |f| %>
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to 'Cancel', casos_path, :class => 'btn' %>
<%=render :partial=>"shared/breadcrumbs", :locals=>{:model_name=>request.path_parameters[:controller],:model_id=>@caso.id, :parent_model=>nil, :parent_id=>nil}%>

  <fieldset>
    <legend><%= controller.action_name.capitalize %> Caso</legend>

    <div class="control-group">
      <%= f.label :caso, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :caso, :class => 'text_field' %>
      </div>
    </div>	
	
            <%=f.input :programa_id,:label=>"Programa" do%>
              <%= f.select :programa_id , Programa.all.map{ |c| ["" + c.nivel + "-" + c.programa, c.id] }%>
            <%end%>  

    <div class="control-group">
      <%= f.label :status_del_caso, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :status_del_caso, :class => 'text_field' %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :nombre_del_cliente, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :nombre_del_cliente, :class => 'text_field' %>
      </div>
    </div>

      <%= f.input :fecha_que_se_presenta_el_problema do %>
             <div class="input-append date datepicker" data-date="<%=DateTime.now.strftime('%Y/%m/%d')%>" data-date-format="yyyy/mm/dd">
               <%= f.text_field :fecha_que_se_presenta_el_problema, :readonly => true%>
         <span class="add-on"><i class="icon-th"></i></span>
             </div>  
           <%end%>

      <%= f.input :fecha_estimada_de_resolucion do %>
             <div class="input-append date datepicker" data-date="<%=DateTime.now.strftime('%Y/%m/%d')%>" data-date-format="yyyy/mm/dd">
               <%= f.text_field :fecha_estimada_de_resolucion%>
         <span class="add-on"><i class="icon-th"></i></span>
             </div>  
           <%end%>

    <div class="control-group">
      <%= f.label :ambito_del_problema, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :ambito_del_problema, :class => 'text_field' %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :sintoma_problema, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_area :sintoma_problema, :class => 'text_area' %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :descripcion_del_sintoma_problema, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_area :descripcion_del_sintoma_problema, :class => 'text_area' %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :causa_del_problema, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_area :causa_del_problema, :class => 'text_area' %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :alternativas_de_solucion, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_area :alternativas_de_solucion, :class => 'text_area' %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :solucion, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_area :solucion, :class => 'text_area' %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :comentarios_de_seguimiento_al_problema, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_area :comentarios_de_seguimiento_al_problema, :class => 'text_area' %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :atentido_por, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :atentido_por, :class => 'text_field' %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :resuelto_por, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :resuelto_por, :class => 'text_field' %>
      </div>
    </div>
      <%= f.input :fecha_que_se_soluciono do %>
             <div class="input-append date datepicker" data-date="<%=DateTime.now.strftime('%Y/%m/%d')%>" data-date-format="yyyy/mm/dd">
               <%= f.text_field :fecha_que_se_soluciono%>
         <span class="add-on"><i class="icon-th"></i></span>
             </div>  
           <%end%>
           
	    <div class="form-actions">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to 'Cancel', casos_path, :class => 'btn' %>
    </div>	
  </fieldset>
<% end %>

<script type="text/javascript">
(function($) {
$(document).ready(function(){
  $('.datepicker').datepicker();
});
})(jQuery);

</script>

app/views/casos/edit.html.erb
<%= render :partial => 'form' %>

app/views/casos/index.html.erb
<h1>Casos</h1>
<table class="table table-striped table-bordered table-condensed">
  <thead>
    <tr>
      <th>ID</th>
      <th>Caso</th>
      <th>Created at</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @casos.each do |caso| %>
      <tr>
        <td><%= caso.id %></td>
        <td><%= link_to caso.caso, caso_path(caso) %></td>
        <td><%= caso.created_at %></td>
        <td>
          <%= link_to 'Edit', edit_caso_path(caso), :class => 'btn btn-mini' %>
          <%= link_to 'Destroy', caso_path(caso), :method => :delete, :confirm => 'Are you sure?', :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'New', new_caso_path, :class => 'btn btn-primary' %>

app/views/casos/new.html.erb
<%= render :partial => 'form' %>

app/views/casos/show.html.erb
<div class="well"><h1>Caso</h1>

<p>
  <b>Caso</b><br>
  <%= @caso.caso %>
</p>

<p>
  <b>Status del caso</b><br>
  <%= @caso.status_del_caso %>
</p>

<p>
  <b>Nombre del cliente</b><br>
  <%= @caso.nombre_del_cliente %>
</p>

<p>
  <b>Fecha que se presenta el problema</b><br>
  <%= @caso.fecha_que_se_presenta_el_problema %>
</p>

<p>
  <b>Fecha estimada de resolucion</b><br>
  <%= @caso.fecha_estimada_de_resolucion %>
</p>

<p>
  <b>Ambito del problema</b><br>
  <%= @caso.ambito_del_problema %>
</p>

<p>
  <b>Sintoma problema</b><br>
  <%= @caso.sintoma_problema %>
</p>

<p>
  <b>Descripcion del sintoma problema</b><br>
  <%= @caso.descripcion_del_sintoma_problema %>
</p>

<p>
  <b>Causa del problema</b><br>
  <%= @caso.causa_del_problema %>
</p>

<p>
  <b>Alternativas de solucion</b><br>
  <%= @caso.alternativas_de_solucion %>
</p>

<p>
  <b>Solucion</b><br>
  <%= @caso.solucion %>
</p>

<p>
  <b>Comentarios de seguimiento al problema</b><br>
  <%= @caso.comentarios_de_seguimiento_al_problema %>
</p>

<p>
  <b>Atentido por</b><br>
  <%= @caso.atentido_por %>
</p>

<p>
  <b>Resuelto por</b><br>
  <%= @caso.resuelto_por %>
</p>

<p>
  <b>Fecha que se soluciono</b><br>
  <%= @caso.fecha_que_se_soluciono %>
</p></div>

<div class="form-actions">
  <%= link_to 'Back', casos_path, :class => 'btn'  %>
  <%= link_to 'Edit', edit_caso_path(@caso), :class => 'btn' %>
  <%= link_to 'Delete', caso_path(@caso), :method => 'delete', :confirm => 'Are you sure?', :class => 'btn btn-danger' %>
</div>