config/routes.rb
ProtoCRM3::Application.routes.draw do

match "web" => "prospectos#webtest", as: :web
  resources :searches

  resources :efectividads

  resources :duracion_en_textos

  resources :configuraciones

  resources :dictamen_psicometria

  resources :dictamen_paas

  resources :report_directions

  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  resources :comments do
    resources :comments
  end

  resources :articles do
    resources :comments
  end

  


  resources :rpms

  resources :histories

  resources :status_ref_pago_inscs

  resources :status_del_examinado_psicos

  resources :status_del_examinado_entrevista


  resources :modalidads

  resources :role_permisions

  resources :roles

  resources :metas_globales

  resources :contactos

  resources :equipo_de_alto_rendimientos

  resources :nacional_de_aperturas

  resources :division_territorials

  resources :colegiaturas

  resources :oferta_educativas

  resources :mi_plan_estrategico_de_promocion_peps

  resources :achievments

  resources :meta

  resources :reportlines

  resources :grupos

  resources :tweets

  resources :subsedes

  resources :events

  resources :posts

  resources :campana_socials

  resources :authentications

  resources :imports

  resources :reportsortbies

  resources :reportparams

  resources :reports

  resources :statics

  resources :correos

  resources :live_reports

  resources :status_del_pago_de_la_inscripcions

  resources :status_de_la_inscripcions

  resources :status_del_admitidos

  resources :status_de_la_notificacions

  resources :status_de_admisions

  resources :status_del_examinado_paas

  resources :status_del_tramite_de_becas

  resources :status_de_pago_eses

  resources :status_de_eses

  resources :tipo_de_admisions

  resources :status_de_pago_de_examen_de_admisions

  resources :status_de_la_accion_1s

  resources :status_de_interes_de_prospecto_validados

  resources :periodo_para_ingresars

  resources :turnos

  resources :nivels

  resources :programa_de_interes

  resources :municipio_de_la_preparatoria_o_universidad_de_origens

  resources :employmentships

  resources :dashboards

  resources :llamadas

  resources :preparatoria_o_universidad_de_origens

  resources :memos

  resources :attachments

  resources :tareas

  resources :barra_favoritos

  resources :favoritos

  resources :ultimo_grado_de_estudios

  resources :nacionalidads

  resources :pregunta

  resources :casos

  resources :equipo_promocions

  resources :programas

  resources :territorios

  resources :plan_de_venta

  resources :finalidad_cultivos

  resources :comentarios_estrategia

  resources :estrategia_promocionals

  resources :mercado_meta


  resources :purges
  resources :inscritos
  resources :admitidos
  resources :examinados
  resources :solicitantes
  resources :prospectos

resources :prospectos, only: :index do
    match 'advanced_search' => 'prospectos#advanced_search',
          on: :collection, via: [:get, :post], as: :advanced_search
  end

  resources :sedes

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks",:sessions => "sessions" }
  resources :users
  
 devise_for :prospectos, :skip => [:webtest] 
  root :to => "homes#force_redirect"
 
  
  match "/solicitantes/:id/convertir_solicitante" => "solicitantes#convertir_solicitante", as: :convertir_solicitante
  match "/examinados/:id/convertir_examinado" => "examinados#convertir_examinado", as: :convertir_examinado
  match "/admitidos/:id/convertir_admitido" => "admitidos#convertir_admitido", as: :convertir_admitido
  match "/prospectos/:id/validar" => "prospectos#validar", as: :validar,:validado=>false
  match "/prospectos/:id/convertir" => "prospectos#convertir", as: :convertir, :validado=>true
  match "/multiexport" => "prospectos#multiexport"
  match "/purgeprospectos" => "prospectos#purgeprospectos"
  match "/borrarprospectosinvalidos" => "prospectos#borrarprospectosinvalidos"

  match "/multiexports" => "prospectos#multiexports"
  match "/multiexporta" => "prospectos#multiexporta"
  match "/multiexporte" => "prospectos#multiexporte"
  match "/multiexporti" => "prospectos#multiexporti"
  match "/mostrarmultiple" => "prospectos#mostrarmultiple"
  match "/cambiarmultiple" => "prospectos#cambiarmultiple"
  match "/webtest" => "prospectos#webtest"

  match "/inscritos/:id/convertir_en_admitido" => "inscritos#convertir_en_admitido", as: :convertir_en_admitido





  match 'saved_search_add' => "searches#saved_search", as: :saved_search
  match 'redir_to_saved' => "searches#redir_to_saved", as: :redir_to_saved
  
  

  
  match "/purge_admitidos"=>"purges#purge_admitidos",as: :purge_admitidos
  match "/purge_examinados"=>"purges#purge_examinados",as: :purge_examinados
  match "/purge_inscritos"=>"purges#purge_inscritos",as: :purge_inscritos
  match "/purge_prospectos"=>"purges#purge_prospectos",as: :purge_prospectos
  match "/purge_sedes"=>"purges#purge_sedes",as: :purge_sedes
  match "/purge_solicitantes"=>"purges#purge_solicitantes",as: :purge_solicitantes
  match "/purge_users"=>"purges#purge_users",as: :purge_users
  match "/purge_all"=>"purges#purge_all",as: :purge_all
  match "/purge_test"=>"purges#purge_test",as: :purge_test

  match "/home"=>"homes#index",as: :home

  
  match "/empleados" => "dashboards#empleados", as: :empleados
  match "/rcircular" => "dashboards#rcircular", as: :rcircular
  match "/rsemanal" => "dashboards#rsemanal", as: :rcircular

  match "/miscorreos" => "statics#miscorreos", as: :miscorreos
  match "/correosenviados" => "statics#correosenviados", as: :correosenviados



  match "/enviandocorreos" => "correos#enviandocorreos", as: :enviandocorreos
  match "/send_correo_individually" => "correos#send_correo_individually", as: :send_correo_individually
  

  match "/campanasenviadas" => "statics#campanasenviadas", as: :campanasenviadas

  match "/prospectos/:id/printview" => "prospectos#printview", as: :printview
  match "/prospectos/:id/printviewpdf" => "prospectos#printviewpdf", as: :printviewpdf

  match "/achievments/:id/printview" => "achievments#printview", as: :printview

  match "/admitidos/:id/printview" => "admitidos#printview", as: :printview
  match "/admitidos/:id/printviewpdf" => "admitidos#printviewpdf", as: :printviewpdf

  match "/reports/:id/printview" => "reports#printview", as: :printview
  match "/solicitantes/:id/printview" => "solicitantes#printview", as: :printview
  match "/solicitantes/:id/printviewpdf" => "solicitantes#printviewpdf", as: :printviewpdf

  match "/examinados/:id/printview" => "examinados#printview", as: :printview
  match "/examinados/:id/printviewpdf" => "examinados#printviewpdf", as: :printviewpdf

  match "/inscritos/:id/printview" => "inscritos#printview", as: :printview
  match "/inscritos/:id/printviewpdf" => "inscritos#printviewpdf", as: :printviewpdf

  match "/admitidos/:id/printview" => "admitidos#printview", as: :printview
  match "/inscritos/:id/printview" => "inscritos#printview", as: :printview
  match "/rpms/:id/printview" => "rpms#printview", as: :printview


  match "/programas/:id/borrar" => "programas#borrar", as: :borrar
  match "/programas/:id/masschange" => "programas#masschange", as: :masschange



  match "/prospectos/:id/resumen"=>"prospectos#resumen", as: :resumen
  
  match "/reports/:id/imprimir" => "reports#imprimir", as: :imprimir
  match "/rpms/:id/imprimir" => "rpms#imprimir", as: :imprimir_rpm
  match "/imports/:id/uploadcsv" => "imports#uploadcsv", as: :uploadcsv

  
  match "/correos/:id/send_correo" => "correos#send_correo", as: :send_correo
  match "/correos/:id/send_correo_individually" => "correos#send_correo_individually", as: :send_correo_individually
  match "/tweets/:id/send_tweet" => "tweets#send_tweet", as: :send_tweet

  match '/auth/:provider/callback' => 'authentications#create'
  match '/auth/google_apps/callback' => 'authentications#create'
  match '/opciones' => 'dashboards#opciones', as: :opciones
  match '/mispendientes' => 'dashboards#mispendientes', as: :mispendientes
  match '/stweet' => 'homes#stweet', as: :stweet

  match '/home2' => 'homes#home2', as: :home2
match "/posts/:id/send_post" => "posts#send_post", as: :send_post

  match "versions/:id/revert" => "versions#revert", :as => "revert_version"



match "/llamadas/:id/convertir_llamada" => "llamadas#convertir_llamada", as: :convertir_llamada
match "/memos/:id/convertir_memo" => "memos#convertir_memo", as: :convertir_memo
match "/tareas/:id/convertir_tarea" => "tareas#convertir_tarea", as: :convertir_tarea












end

app/models/solicitante.rb
class Solicitante < ActiveRecord::Base
	has_many :prospectos, :dependent => :destroy
	
	has_many :nacionalidad, through: :prospectos
	has_many :user, through: :prospectos
	has_many :sede, through: :prospectos
	has_many :subsede, through: :prospectos
	has_many :mercado_metum, through: :prospectos
	has_many :territorio, through: :prospectos
	has_many :plan_de_ventum, through: :prospectos
	has_many :programa, through: :prospectos
	has_many :grupo, through: :prospectos

	has_many :medio_de_contactos, through: :prospectos
	has_many :interes_basicos, through: :prospectos
	has_many :interes_academicos, through: :prospectos
	has_many :accion_estrategicas, through: :prospectos
	has_many :plan_de_descuentos, through: :prospectos


	has_many :becacreditos, :dependent => :destroy
	belongs_to :examinado
	belongs_to :status_de_pago_de_examen_de_admision
	belongs_to :tipo_de_admision

	accepts_nested_attributes_for :becacreditos, :reject_if => :all_blank, :allow_destroy => true
	accepts_nested_attributes_for :prospectos, :reject_if => :all_blank, :allow_destroy => true
	#accepts_nested_attributes_for :prospectos, :reject_if => :all_blank, :allow_destroy => true
	has_paper_trail
	
	default_value_for :hora_programada_PAA do
    Time.new.beginning_of_day
	end
	default_value_for :hora_programada_pscicometrico do
    Time.new.beginning_of_day
	end
  	default_value_for :hora_programada_entrevistas do
    Time.new.beginning_of_day
	end
end

app/helpers/solicitantes_helper.rb
module SolicitantesHelper
end

app/views/solicitantes/_attribute_fields.html.erb
<span class="fields" data-object-name="<%= f.object_name %>">
  <%= f.attribute_select associations: %w() %>
</span>

app/views/solicitantes/_condition_fields.html.erb
<span class="fields" data-object-name="<%= f.object_name %>">
  <%= f.attribute_fields do |a| %>
    <%= a.attribute_select associations: [:prospectos,:becacreditos,:prospectos_nacionalidad, :prospectos_programa,:prospectos_user,:prospectos_sede,:prospectos_grupo,:prospectos_direccions,:prospectos_interes_basicos,:prospectos_interes_academicos,:prospectos_plan_de_descuentos] %>
  <% end %>
  <%= f.predicate_select %>
  <%= f.value_fields do |v| %>
    <%= v.text_field :value %>
  <% end %>
  <%= button_to_remove_fields "remove", f %>
</span>
<br/>

app/views/solicitantes/_form.html.erb
  <%= simple_form_for @solicitante, :html => { :class => 'form-horizontal' ,:onsubmit=>"return confirm('Estas seguro de querer continuar?');"} do |f| %>
      <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to 'Cancel', solicitantes_path,:confirm => "Estas seguro de querer continuar?", :class => 'btn' %>
    <%if request.path_parameters[:action]== "edit" %>
      <%if not @solicitante.isexaminado?%>
        <%= link_to 'Convertir en Examinado', convertir_solicitante_path,:confirm => "Estas seguro de querer continuar?", :class=>'btn btn-info avoid', :method=>'post', :id=>'convertir'%> 
      <%end%>
    <%end%>
<%=render :partial=>"shared/breadcrumbs", :locals=>{:model_name=>request.path_parameters[:controller],:model_id=>@solicitante.id, :parent_model=>nil, :parent_id=>nil}%>
<%= render :partial => "solicitanteNav"%>
<%=render :partial=>"shared/edit_solicitantes", :locals=>{:f=>f}%>
<%=render :partial=>"shared/edit_prospectos", :locals=>{:f=>f}%>
<div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to 'Cancel', solicitantes_path,:confirm => "Estas seguro de querer continuar?", :class => 'btn' %>
    <%if request.path_parameters[:action]== "edit" %>
      <%if not @solicitante.isexaminado?%>
        <%= link_to 'Convertir en Examinado', convertir_solicitante_path,:confirm => "Estas seguro de querer continuar?", :class=>'btn btn-info avoid', :method=>'post', :id=>'convertir'%> 
      <%end%>
    <%end%>
</div>    
<%=render :partial=>"shared/tabed_actions", :locals=>{:prospecto_id=>@solicitante.id,:real_id=>@solicitante.prospectos.first.id,:tareas=>@tareas,:memos=>@memos,:llamadas=>@llamadas,:correos=>@correos,:attachments=>@attachments}%>
<div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to 'Cancel', solicitantes_path,:confirm => "Estas seguro de querer continuar?", :class => 'btn' %>
    <%if request.path_parameters[:action]== "edit" %>
      <%if not @solicitante.isexaminado?%>
        <%= link_to 'Convertir en Examinado', convertir_solicitante_path,:confirm => "Estas seguro de querer continuar?", :class=>'btn btn-info avoid', :method=>'post', :id=>'convertir'%> 
      <%end%>
    <%end%>
</div>    
<% end %>
<script type="text/javascript">
(function($) {
$(document).ready(function(){
  $('.datepicker').datepicker();
});
})(jQuery);

</script>

app/views/solicitantes/_grouping_fields.html.erb
<fieldset class="fields" data-object-name="<%= f.object_name %>">
  <legend>Coincide <%= f.combinator_select %> con <%= button_to_remove_fields "remove", f %></legend>
  <%= f.condition_fields do |c| %>
    <%= render 'condition_fields', f: c %>
  <% end %>
  <%= button_to_add_fields "Agregar condicion", f, :condition %>

  <%= f.grouping_fields do |g| %>
    <%= render 'grouping_fields', f: g %>
  <% end %>
  <%= button_to_nest_fields "Agregar grupo de condicion", :grouping %>
</fieldset>
<br/>

app/views/solicitantes/_solicitanteNav.html.erb
        <ul id="tab" class="nav nav-tabs">
          <li class="active"><a href="#solicitante" data-toggle="tab">Solicitante</a></li>
          <li><a href="#becacredito" data-toggle="tab">Beca Credito</a></li>
          <li><a href="#informacion" data-toggle="tab">Informacion Personal</a></li>
            <li><a href="#direccion" data-toggle="tab">Dirección</a></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">Intereses <b class="caret"></b></a>
              <ul class="dropdown-menu">
                <li><a href="#interesbasico" data-toggle="tab">Interes Basico</a></li>
                <li><a href="#interesacademico" data-toggle="tab">Interes Academico</a></li>
              </ul>
            </li>            
            <li><a href="#medio" data-toggle="tab">Medio de Contacto</a></li>
            <li><a href="#plandescuentos" data-toggle="tab">Plan de descuentos</a></li> 
            <li><a href="#history<%=@solicitante.prospectos.first.id%>" data-toggle="tab">Historial</a></li>          
            <!--<li><a href="#compartido" data-toggle="tab">Compartido</a></li>-->
        </ul>
        <div id="myTabContent" class="tab-content">
          <%=render :partial=>"shared/history", :locals=>{:model_name=>"prospectos",:model_id=>@solicitante.prospectos.first.id, :parent_model=>nil}%>

app/views/solicitantes/_sort_fields.html.erb
<span class="fields" data-object-name="<%= f.object_name %>">
  <%= f.sort_select %>
  <%= button_to_remove_fields "remove", f %>
</span>
<br/>

app/views/solicitantes/_value_fields.html.erb
<span class="fields value" data-object-name="<%= f.object_name %>">
  <%= f.text_field :value %>
</span>
<br/>

app/views/solicitantes/edit.html.erb
<%= render :partial => 'form' %>

app/views/solicitantes/index.html.erb
<h1>Solicitantes</h1>
<%if @solicitantes.total_entries > 100%> 


 
        <%= link_to raw("<i class=""icon-arrow-down""></i>Exportar a Excel<i class=""icon-arrow-down""></i>"), multiexports_path, :class => 'btn btn-mini btn-info' %>  


 
      <%else%>   


 
         <%= link_to raw("<i class=""icon-arrow-down""></i>Exportar a Excel<i class=""icon-arrow-down""></i>"), solicitantes_path(params.merge(format: 'xls')), :class => 'btn btn-mini btn-info' %>   


 
    <%end%> 
    
<hr/>
<style type="text/css">
fieldset {
  display: block;
  -webkit-margin-start: 2px;
  -webkit-margin-end: 2px;
  -webkit-padding-before: 0.35em;
  -webkit-padding-start: 0.75em;
  -webkit-padding-end: 0.75em;
  -webkit-padding-after: 0.625em;
  border: 2px groove threedface;
}
legend
{
margin-bottom: 0!important;
border-bottom: 0px solid #e5e5e5!important;
}
</style>
<%=render :partial=>"shared/save_search", :locals=>{:path_to_look_for=>solicitantes_path, :renderForChange=>false}%>
  <%=@solicitantes.size%> registros de un total de <%=@solicitantes.total_entries%>
<table class="table table-striped table-bordered table-condensed" id="MyTable">
  <thead>
    <tr>
      <th><%= sort_link @q, :id, {}, :method => :get %></th>
      <th><%= sort_link @q, :nombre, {}, :method => :get %></th>
      <th><%= sort_link @q, :apellido_paterno, {}, :method => :get %></th>
      <th><%= sort_link @q, :apellido_materno, {}, :method => :get %></th>
      <th><%= sort_link @q, :programa, {}, :method => :get %></th>
      <th><%= sort_link @q, :created_at, {}, :method => :get %></th>
      <th>Acciones</th>
    </tr>
  </thead>
  <tbody>
    <% @solicitantes.each do |solicitante| %>
                         <%tareastatus=""%> 
                          <%tareas = Tarea.where(:model_name=>"solicitantes").where(:model_id=>solicitante.id,:pendiente=>true).all%>
                            <%if tareas != nil%>
                                <%tareas.each do |tarea|%>
                                    <%if tarea.fecha_de_inicio_de_la_tarea!=nil && tarea.fecha_de_inicio_de_la_tarea < Date.today - 2%>
                                      <%tareastatus="redrow whitetigger"%>
                                    <%end%>                
                                    <%if tarea.fecha_de_inicio_de_la_tarea != nil && tarea.fecha_de_inicio_de_la_tarea == Date.today - 1%>
                                      <%tareastatus="orangerow whitetigger"%>
                                    <%end%>
                                    <%if tarea.fecha_de_inicio_de_la_tarea != nil && tarea.fecha_de_inicio_de_la_tarea == Date.today%>
                                      <% tareastatus="navyrow linkcolor"%>
                                    <%end%>
                                    <%if tarea.fecha_de_inicio_de_la_tarea!= nil && tarea.fecha_de_inicio_de_la_tarea == Date.tomorrow%>
                                      <%tareastatus="stonerow linkcolor"%>
                                    <%end%>
                                <%end%>
                            <%end%>
                          <%tareas = Llamada.where(:model_name=>"solicitantes").where(:model_id=>solicitante.id,:pendiente=>true).all%>
                            <%if tareas != nil%>
                                <%tareas.each do |tarea|%>
                                    <%if tarea.inicio_de_la_llamada!=nil && tarea.inicio_de_la_llamada < Date.today - 2%>
                                      <%tareastatus="redrow whitetigger"%>
                                    <%end%>                
                                    <%if tarea.inicio_de_la_llamada != nil && tarea.inicio_de_la_llamada == Date.today - 1%>
                                      <%tareastatus="orangerow whitetigger"%>
                                    <%end%>
                                    <%if tarea.inicio_de_la_llamada != nil && tarea.inicio_de_la_llamada == Date.today%>
                                      <% tareastatus="navyrow linkcolor"%>
                                    <%end%>
                                    <%if tarea.inicio_de_la_llamada!= nil && tarea.inicio_de_la_llamada == Date.tomorrow%>
                                      <%tareastatus="stonerow linkcolor"%>

                                    <%end%>
                                <%end%>
                            <%end%> 
                            <%tareas = Memo.where(:model_name=>"solicitantes").where(:model_id=>solicitante.id,:pendiente=>true).size%>                                            
                            <%if tareas > 0
                                tareastatus="orangerow linkcolor"
                              end%>        
      <tr>
        <%if solicitante.prospectos.first == nil%>
          <td><%= solicitante.id %></td>
          <td>Invalido</td>
          <td>Invalido</td>
          <td>Invalido</td>
          <td>Invalido</td>
        <%else%>
          <td><%= solicitante.id %></td>
          <td><%= link_to solicitante.prospectos.first.nombre, solicitante_path(solicitante) %></td>
          <td><%= link_to solicitante.prospectos.first.apellido_paterno, solicitante_path(solicitante) %></td>
          <td><%= link_to solicitante.prospectos.first.apellido_materno, solicitante_path(solicitante) %></td>
          <td><%= link_to solicitante_path(solicitante) do %>
              <%=solicitante.prospectos.first.programa.nivel rescue nil%> - <%=solicitante.prospectos.first.programa.programa rescue nil%>
              <%end%>
            </td>        
        <%end%>


        <td><%= solicitante.created_at %></td>
        <td>
        <%if tareastatus != ""%>
          <%= link_to '<i class="icon-info-sign"></i> Acciones Pendientes'.html_safe, edit_solicitante_path(solicitante,:anchor=>"tareas"),:class=>'btn btn-warning btn-mini zero2'%>
        <%end%>              
          <%= link_to 'Edit', edit_solicitante_path(solicitante), :class => 'btn btn-mini' %>
          <%= link_to 'Destroy', solicitante_path(solicitante), :method => :delete, :confirm => 'Are you sure?', :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
    <%= hidden_field_tag :direction, params[:direction] %>
    <%= hidden_field_tag :sort, params[:sort] %>
<%= will_paginate @solicitantes %>
<br/>
<%=@solicitantes.size%> registros de un total de <%=@solicitantes.total_entries%>
<!--<%= link_to 'New', new_solicitante_path, :class => 'btn btn-primary' %>-->

app/views/solicitantes/new.html.erb
<%= render :partial => 'form' %>

app/views/solicitantes/show.html.erb
<%=render :partial=>"shared/breadcrumbs", :locals=>{:model_name=>request.path_parameters[:controller],:model_id=>@solicitante.id, :parent_model=>nil, :parent_id=>nil}%>
<%= render :partial => "solicitanteNav"%>
<%=render :partial=>"shared/show_solicitantes", :locals=>{:f=>@solicitante,:isactive=>" in active "}%>

<div class="form-actions">
  <%= link_to 'Back', solicitantes_path, :class => 'btn'  %>
  <%= link_to 'Edit', edit_solicitante_path(@solicitante), :class => 'btn' %>
        <%if not @solicitante.isexaminado?%>
        <%= link_to 'Convertir en Examinado', convertir_solicitante_path,:confirm => "Estas seguro de querer continuar?", :class=>'btn btn-info', :method=>'post', :id=>'convertir'%> 
      <%end%>
  <%= link_to 'Delete', solicitante_path(@solicitante), :method => 'delete', :confirm => 'Are you sure?', :class => 'btn btn-danger' %>
</div>