config/routes.rb
ProtoCRM3::Application.routes.draw do

match "web" => "prospectos#webtest", as: :web
  resources :searches

  resources :efectividads

  resources :duracion_en_textos

  resources :configuraciones

  resources :dictamen_psicometria

  resources :dictamen_paas

  resources :report_directions

  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  resources :comments do
    resources :comments
  end

  resources :articles do
    resources :comments
  end

  


  resources :rpms

  resources :histories

  resources :status_ref_pago_inscs

  resources :status_del_examinado_psicos

  resources :status_del_examinado_entrevista


  resources :modalidads

  resources :role_permisions

  resources :roles

  resources :metas_globales

  resources :contactos

  resources :equipo_de_alto_rendimientos

  resources :nacional_de_aperturas

  resources :division_territorials

  resources :colegiaturas

  resources :oferta_educativas

  resources :mi_plan_estrategico_de_promocion_peps

  resources :achievments

  resources :meta

  resources :reportlines

  resources :grupos

  resources :tweets

  resources :subsedes

  resources :events

  resources :posts

  resources :campana_socials

  resources :authentications

  resources :imports

  resources :reportsortbies

  resources :reportparams

  resources :reports

  resources :statics

  resources :correos

  resources :live_reports

  resources :status_del_pago_de_la_inscripcions

  resources :status_de_la_inscripcions

  resources :status_del_admitidos

  resources :status_de_la_notificacions

  resources :status_de_admisions

  resources :status_del_examinado_paas

  resources :status_del_tramite_de_becas

  resources :status_de_pago_eses

  resources :status_de_eses

  resources :tipo_de_admisions

  resources :status_de_pago_de_examen_de_admisions

  resources :status_de_la_accion_1s

  resources :status_de_interes_de_prospecto_validados

  resources :periodo_para_ingresars

  resources :turnos

  resources :nivels

  resources :programa_de_interes

  resources :municipio_de_la_preparatoria_o_universidad_de_origens

  resources :employmentships

  resources :dashboards

  resources :llamadas

  resources :preparatoria_o_universidad_de_origens

  resources :memos

  resources :attachments

  resources :tareas

  resources :barra_favoritos

  resources :favoritos

  resources :ultimo_grado_de_estudios

  resources :nacionalidads

  resources :pregunta

  resources :casos

  resources :equipo_promocions

  resources :programas

  resources :territorios

  resources :plan_de_venta

  resources :finalidad_cultivos

  resources :comentarios_estrategia

  resources :estrategia_promocionals

  resources :mercado_meta


  resources :purges
  resources :inscritos
  resources :admitidos
  resources :examinados
  resources :solicitantes
  resources :prospectos

resources :prospectos, only: :index do
    match 'advanced_search' => 'prospectos#advanced_search',
          on: :collection, via: [:get, :post], as: :advanced_search
  end

  resources :sedes

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks",:sessions => "sessions" }
  resources :users
  
 devise_for :prospectos, :skip => [:webtest] 
  root :to => "homes#force_redirect"
 
  
  match "/solicitantes/:id/convertir_solicitante" => "solicitantes#convertir_solicitante", as: :convertir_solicitante
  match "/examinados/:id/convertir_examinado" => "examinados#convertir_examinado", as: :convertir_examinado
  match "/admitidos/:id/convertir_admitido" => "admitidos#convertir_admitido", as: :convertir_admitido
  match "/prospectos/:id/validar" => "prospectos#validar", as: :validar,:validado=>false
  match "/prospectos/:id/convertir" => "prospectos#convertir", as: :convertir, :validado=>true
  match "/multiexport" => "prospectos#multiexport"
  match "/purgeprospectos" => "prospectos#purgeprospectos"
  match "/borrarprospectosinvalidos" => "prospectos#borrarprospectosinvalidos"

  match "/multiexports" => "prospectos#multiexports"
  match "/multiexporta" => "prospectos#multiexporta"
  match "/multiexporte" => "prospectos#multiexporte"
  match "/multiexporti" => "prospectos#multiexporti"
  match "/mostrarmultiple" => "prospectos#mostrarmultiple"
  match "/cambiarmultiple" => "prospectos#cambiarmultiple"
  match "/webtest" => "prospectos#webtest"

  match "/inscritos/:id/convertir_en_admitido" => "inscritos#convertir_en_admitido", as: :convertir_en_admitido





  match 'saved_search_add' => "searches#saved_search", as: :saved_search
  match 'redir_to_saved' => "searches#redir_to_saved", as: :redir_to_saved
  
  

  
  match "/purge_admitidos"=>"purges#purge_admitidos",as: :purge_admitidos
  match "/purge_examinados"=>"purges#purge_examinados",as: :purge_examinados
  match "/purge_inscritos"=>"purges#purge_inscritos",as: :purge_inscritos
  match "/purge_prospectos"=>"purges#purge_prospectos",as: :purge_prospectos
  match "/purge_sedes"=>"purges#purge_sedes",as: :purge_sedes
  match "/purge_solicitantes"=>"purges#purge_solicitantes",as: :purge_solicitantes
  match "/purge_users"=>"purges#purge_users",as: :purge_users
  match "/purge_all"=>"purges#purge_all",as: :purge_all
  match "/purge_test"=>"purges#purge_test",as: :purge_test

  match "/home"=>"homes#index",as: :home

  
  match "/empleados" => "dashboards#empleados", as: :empleados
  match "/rcircular" => "dashboards#rcircular", as: :rcircular
  match "/rsemanal" => "dashboards#rsemanal", as: :rcircular

  match "/miscorreos" => "statics#miscorreos", as: :miscorreos
  match "/correosenviados" => "statics#correosenviados", as: :correosenviados



  match "/enviandocorreos" => "correos#enviandocorreos", as: :enviandocorreos
  match "/send_correo_individually" => "correos#send_correo_individually", as: :send_correo_individually
  

  match "/campanasenviadas" => "statics#campanasenviadas", as: :campanasenviadas

  match "/prospectos/:id/printview" => "prospectos#printview", as: :printview
  match "/prospectos/:id/printviewpdf" => "prospectos#printviewpdf", as: :printviewpdf

  match "/achievments/:id/printview" => "achievments#printview", as: :printview

  match "/admitidos/:id/printview" => "admitidos#printview", as: :printview
  match "/admitidos/:id/printviewpdf" => "admitidos#printviewpdf", as: :printviewpdf

  match "/reports/:id/printview" => "reports#printview", as: :printview
  match "/solicitantes/:id/printview" => "solicitantes#printview", as: :printview
  match "/solicitantes/:id/printviewpdf" => "solicitantes#printviewpdf", as: :printviewpdf

  match "/examinados/:id/printview" => "examinados#printview", as: :printview
  match "/examinados/:id/printviewpdf" => "examinados#printviewpdf", as: :printviewpdf

  match "/inscritos/:id/printview" => "inscritos#printview", as: :printview
  match "/inscritos/:id/printviewpdf" => "inscritos#printviewpdf", as: :printviewpdf

  match "/admitidos/:id/printview" => "admitidos#printview", as: :printview
  match "/inscritos/:id/printview" => "inscritos#printview", as: :printview
  match "/rpms/:id/printview" => "rpms#printview", as: :printview


  match "/programas/:id/borrar" => "programas#borrar", as: :borrar
  match "/programas/:id/masschange" => "programas#masschange", as: :masschange



  match "/prospectos/:id/resumen"=>"prospectos#resumen", as: :resumen
  
  match "/reports/:id/imprimir" => "reports#imprimir", as: :imprimir
  match "/rpms/:id/imprimir" => "rpms#imprimir", as: :imprimir_rpm
  match "/imports/:id/uploadcsv" => "imports#uploadcsv", as: :uploadcsv

  
  match "/correos/:id/send_correo" => "correos#send_correo", as: :send_correo
  match "/correos/:id/send_correo_individually" => "correos#send_correo_individually", as: :send_correo_individually
  match "/tweets/:id/send_tweet" => "tweets#send_tweet", as: :send_tweet

  match '/auth/:provider/callback' => 'authentications#create'
  match '/auth/google_apps/callback' => 'authentications#create'
  match '/opciones' => 'dashboards#opciones', as: :opciones
  match '/mispendientes' => 'dashboards#mispendientes', as: :mispendientes
  match '/stweet' => 'homes#stweet', as: :stweet

  match '/home2' => 'homes#home2', as: :home2
match "/posts/:id/send_post" => "posts#send_post", as: :send_post

  match "versions/:id/revert" => "versions#revert", :as => "revert_version"



match "/llamadas/:id/convertir_llamada" => "llamadas#convertir_llamada", as: :convertir_llamada
match "/memos/:id/convertir_memo" => "memos#convertir_memo", as: :convertir_memo
match "/tareas/:id/convertir_tarea" => "tareas#convertir_tarea", as: :convertir_tarea












end

app/models/report.rb
class Report < ActiveRecord::Base
	serialize :column_names
	has_many :reportparams, :dependent=>:destroy
	has_many :reportsortbies, :dependent=>:destroy
	has_many :reportlines, :dependent=>:destroy
	accepts_nested_attributes_for :reportparams, :reject_if => lambda { |a| a[:fieldname].blank? }, :allow_destroy => true
	accepts_nested_attributes_for :reportsortbies, :reject_if => lambda { |a| a[:fieldname].blank? }, :allow_destroy => true
	accepts_nested_attributes_for :reportlines, :reject_if => lambda { |a| a[:modulo].blank? }, :allow_destroy => true
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/views/reports/_form.html.erb
<%=render :partial=>"shared/breadcrumbs", :locals=>{:model_name=>request.path_parameters[:controller],:model_id=>@report.id, :parent_model=>nil}%>
<%= simple_form_for @report, :html => { :class => 'form-horizontal',:id=>"forma" } do |f| %>
    <fieldset>
      <legend>Agregar Datos principales</legend>
        <%= f.input :nombre %>
        <%= f.input :descripcion, :as => :text ,:input_html => { :cols => 50, :rows => 3 }  %>

        <% if request.path_parameters[:action] =="edit" %>
          <%= f.input :por_pagina%>
          <%columnas=ActiveRecord::Base.connection.columns(@report.table)%>          
          <%= f.input :table, :collection=>ActiveRecord::Base.connection.tables,:include_blank => false, :label=>"Modulo",:disabled=>true,:hint=>"Una vez que selecciones el modulo no es posible cambiarlo."%> 
          <% if @report.column_names == "" %>      
              <%= f.input :column_names, :collection=>columnas.map{|c| [c.name.humanize,c.name] }.sort,:include_blank=>false,:input_html => { :multiple=>"multiple" } %>
          <% else %>
              <%= f.input :column_names, :collection=>columnas.map{|c| [c.name.humanize,c.name] }.sort,:include_blank=>false,:input_html => { :multiple=>"multiple" } %>                  
          <% end %>
        <%else%>   
          <%= f.input :por_pagina, :input_html=>{:value=>5}%>
          <%= f.input :table, :collection=>ActiveRecord::Base.connection.tables.sort,:include_blank => false, :label=>"Modulo",:hint=>"Una vez que selecciones el modulo no es posible cambiarlo."%>
        <%end%>
    </fieldset>
      <% if request.path_parameters[:action] =="edit" %>
      <fieldset>
        <legend>Parametros</legend>
        <%= f.simple_fields_for :reportparams, :html => { :class => 'form-inline' } do |fg| %> 
          <%= render 'reportparam_fields', :f => fg %>
        <% end %>
        <div class="fields">
          <%= link_to_add_fields "Agregar Nuevo Parametro", f, :reportparams %>
        </div>
      </fieldset>
      <fieldset>
        <legend>Ordenar Por</legend>
        <%= f.simple_fields_for :reportsortbies, :html => { :class => 'form-inline' } do |fx| %> 
          <%= render 'reportsortbies_fields', :f => fx %>
        <% end %>
        <div class="fields">
          <%= link_to_add_fields "Agregar Nuevo Ordenar Por", f, :reportsortbies %>
        </div>
      </fieldset>
      <fieldset>
        <legend>Lineas Personalizadas</legend>
        <%= f.simple_fields_for :reportlines, :html => { :class => 'form-inline' } do |fx| %> 
          <%= render 'reportline_fields', :f => fx %>
        <% end %>
        <div class="fields">
          <%= link_to_add_fields "Agregar Nueva Linea Personalizada", f, :reportlines %>
        </div>        
        </fieldset>
      <%end%>
    <fieldset>
      <legend>Guardar/Imprimir</legend>
    <div class="form-actions">
      <% if request.path_parameters[:action] =="edit" %>
        <%= f.submit nil, :class => 'btn btn-primary' ,:value=>"Imprimir"%>
      <%else%>
        <%= f.submit nil, :class => 'btn btn-primary' %>
      <%end%>
      <%= link_to 'Cancel', reports_path, :class => 'btn' %>
    </div>
    </fieldset>
<% end %>
<script type="text/javascript">
(function($) {
$(document).ready(function(){
  $('.datepicker').datepicker();
});
})(jQuery);

</script>

app/views/reports/_reportline_fields.html.erb
<div class="well fields">

  	<%= f.hidden_field :nombre_del_campo%>
  	<%= f.input_field :modulo, :collection=>ActiveRecord::Base.connection.tables,:include_blank => false, :label=>"Modulo",:hint=>"Una vez que selecciones el modulo no es posible cambiarlo."%>
    <%= f.input_field :filtro, :collection => [ "Sumarizar"],:include_blank=>false %>
    <%= f.hidden_field :report_id, :disabled=>true %>
    <%= f.hidden_field :_destroy %>
    <%= link_to_function "Elminar Linea", "if(confirm('Estas seguro?')){remove_fields(this)}", :class => 'btn btn-mini btn-danger' %>

</div>

app/views/reports/_reportparam_fields.html.erb
<div class="well fields">
  
  	<%	columnas=ActiveRecord::Base.connection.columns(@report.table)
	    columnas= columnas + ActiveRecord::Base.connection.columns("direccions")
	    columnas= columnas + ActiveRecord::Base.connection.columns("interes_basicos")
	    columnas= columnas + ActiveRecord::Base.connection.columns("medio_de_contactos")
	    columnas= columnas + ActiveRecord::Base.connection.columns("plan_de_descuentos")
	    columnas = columnas.index_by {|r| r.name.humanize}.values

	    %>
    <%= f.input_field  :fieldname, :collection=>columnas.map{|c| [c.name.humanize,c.name] }.sort,:include_blank=>false %>
    <%= f.input_field :filter, :collection => [ "Igual a", "No Igual a", "Contiene", "Mas grande que", "Mas grande o igual a", "Mas chico que", "Mas chico o igual a"],:include_blank=>false %>
    <!--<%= f.input_field :fieldvalue, :placeholder=>"Valor por defecto" %>-->

	<%
	global=[]
	
	
	goup =[]

	collection =[]
	columnvalue=""
	uno=0
	columnas.each do |column| 
		current=[]
		perfield=[]
		if uno == 0
			perfield.push(Array.new(1," "))
			current.push("Valor por defecto",perfield) 	
			global.push(current)	
			uno =1
		end
		case column.type.to_s
			when "integer"
				if column.name.include? "id" and column.name.size > 2
					columnia=column.name.chomp('_id')
					case columnia 
						when "solicitante"
							if @report.table == "prospectos"
								""
							end
						when "nacionalidad"
							tabla = Nacionalidad.all rescue nil
								if tabla != nil && tabla.size > 0
									tabla.each do |t|
										perfield.push(Array.new(1,t.nacionalidad))
										#perfield.push(Array.new(2,t.id))
									end
									current.push(column.name,perfield)
									#collection.push(tabla.map{|a| [a.nacionalidad]})
								end
						when "user"
							tabla = eval(columnia.camelize.singularize + ".all") rescue nil
								if tabla != nil && tabla.size > 0
									tabla.each do |t|
										perfield.push(Array.new(1,t.username))
										#perfield.push(Array.new(2,t.id))
									end
									current.push(column.name,perfield)
								end							
						when "sede","territorio","grupo"
							tabla = eval(columnia.camelize.singularize + ".all") rescue nil
								if tabla != nil && tabla.size > 0
									tabla.each do |t|
										perfield.push(Array.new(1,t.nombre))
										#perfield.push(Array.new(2,t.id))
									end
									current.push(column.name,perfield)
								end							
						when "programa","plan_de_venta"
							tabla = eval(columnia.camelize.singularize + ".all") rescue nil
								if tabla != nil && tabla.size > 0
									tabla.each do |t|
										perfield.push(Array.new(1,t.programa))
										#perfield.push(Array.new(2,t.id))
									end
									current.push(column.name,perfield)
								end								
						when "plan_de_ventum"
							""
						else
							tabla=eval(columnia.camelize.singularize + ".all") rescue nil
							if tabla != nil && tabla.size > 0
								tabla.each do |t|
									if t.respond_to?(:valor)
										perfield.push(Array.new(1,t.valor))
										#perfield.push(Array.new(2,t.id))
									else
										""
									end
									current.push(column.name,perfield)
								end								
							end
					end
					global.push(current)
				end
			when "float"
				""
			when "string"
				""         
			when "text"
				""  				
			when "boolean"
				case column.name.to_s
				when "sexo"
					perfield.push(Array.new(1,"Masculino"))
					perfield.push(Array.new(1,"Femenino"))
					current.push("sexo",perfield)         
				when "validado"		
					perfield.push(Array.new(1,"Validado"))
					perfield.push(Array.new(1,"No Validado"))
					current.push("validado",perfield)				    
				end    
				global.push(current)
			when "datetime"                              
				""
			when "date"                              
				""
			when "time"                              
				""				
			when "Nacionalidad"   
				tabla=Nacionalidad.all
				#collection.push(column,tabla)
			else 
				#tabla=eval(column.name.camelize.singularize + ".all").map{|a| [a.valor]}
				#if tabla != nil
				#	collection.push(column.name,tabla)
				#end			
		end		
	end

	global.delete_if{|i| i.empty?}
	%> 
	
	<div class="input-append date datepicker" id="dp3" data-date-format="mm/dd/yyyy">
		<%= f.input_field :date_value, :placeholder=>"Valor por defecto"%>
		<span class="add-on"><i class="icon-th"></i></span>
	</div>
	<%= f.input_field :fieldvalue, :disabled=>true , :html => { :class => 'form-inline' }%> 
	<%= f.select :fieldvalue, grouped_options_for_select(global,selected_key =:fieldvalue) , :html => { :class => 'form-inline' }%> 
    <%= f.hidden_field :report_id, :disabled=>true %>
    <%= f.hidden_field :_destroy %>
    <%= link_to_function "Elminar Parametro", "if(confirm('Estas seguro?')){remove_fields(this)}", :class => 'btn btn-mini btn-danger' %>
  
</div>

<script type="text/javascript">
(function($) {
$(document).ready(function(){
	$('.datepicker').datepicker();
});
})(jQuery);

</script>

app/views/reports/_reportsortbies_fields.html.erb
<div class="well fields">
 
  	<%	columnas=ActiveRecord::Base.connection.columns(@report.table)
	  %>  	
    <%= f.input_field :fieldname, :collection=>columnas.map{|c| [c.name.humanize,c.name] }.sort,:include_blank=>false %>
    <%= f.input_field :orden, :collection=>["Ascendente","Descendente"],:include_blank=>false%>
    <%= f.hidden_field :report_id, :disabled=>true %>
    <%= f.hidden_field :_destroy %>
    <%= link_to_function "Elminar Ordernar por", "if(confirm('Estas seguro?')){remove_fields(this)}", :class => 'btn btn-mini btn-danger' %>
 
</div>

app/views/reports/_reportsortby_fields.html.erb
<div class="well fields">
  
  	<%	columnas=ActiveRecord::Base.connection.columns(@report.table)
	  %>    	
    <%= f.input_field :fieldname, :collection=>columnas.map{|c| [c.name.humanize,c.name] }.sort,:include_blank=>false %>
    <%= f.input_field :orden, :collection=>["Ascendente","Descendente"],:include_blank=>false%>
    <%= f.hidden_field :report_id, :disabled=>true %>
    <%= f.hidden_field :_destroy %>
    <%= link_to_function "Elminar Ordernar por", "if(confirm('Estas seguro?')){remove_fields(this)}", :class => 'btn btn-mini btn-danger' %>
 
</div>

app/views/reports/edit.html.erb
<%= render :partial => 'form' %>

app/views/reports/imprimir.html.erb
<%=render :partial=>"shared/breadcrumbs", :locals=>{:model_name=>request.path_parameters[:controller],:model_id=>@report.id, :parent_model=>nil}%>
<h1>Informe <%=@report.id%></h1>
<h3><%=@report.nombre%></h3>
<span class="help-block"><p>Puedes hacer click en los titulos de las columnas para reornenarlas, o moverlas haciendo click en ellas y moviendolas a la izquierda o derecha.</p><p>Addicionalmente cuando hay mas registros que los seleccionados puedes usar las flechas de la parte inferior para navegar entre los registros</p></span>
<div class="well">
  <table class="draggable sortable table table-striped table-bordered table-condensed">
    <thead>
      <tr>
        <%if @report.column_names != nil%>
          <% @report.column_names.each do |column| %>
              <th><a href="#"><%= column.humanize %></a></th>
          <% end %>
        <% end %>
      </tr>
    </thead>
    <tbody>
      <% @informe.each do |informe| %>
        <tr>
          <%if @report.column_names != nil%>
           <% @report.column_names.each do |column| %>
              <%columnvalue = eval("informe" + "." + column)%>
              <%
                case columnvalue.class.to_s
                when "Fixnum"
                  %>
                    <td><%= columnvalue %></td>
                  <%
                when "String"
                    evalpath=eval("edit_" + @report.table.singularize + "_path(informe.id)")
                      %>
                        <td><%=link_to columnvalue, evalpath%></td>
                      <%                    
                when "TrueClass"
                    case column.to_s
                    when "sexo"
                      %>
                        <td><%= (columnvalue) ? "Masculino" : "Femenino" %></td>
                      <%                      
                    when "validado"
                      %>
                        <td><%= (columnvalue) ? "Validado" : "No Validado" %></td>
                      <%                      
                    else
                      %>
                        <td><%= columnvalue %></td>
                      <%            
                    end    
                when "Date"                              
                  %>
                    <td><%= columnvalue %></td>
                  <%
                when "Nacionalidad"                              
                  %>
                    <td><%= columnvalue.nacionalidad %></td>
                  <%                
                else
                    %>
                      <td><%= (columnvalue.respond_to?(:valor)) ? columnvalue.valor  : columnvalue %></td>
                    <%                                                          
                end

              %>
            <% end %>  
          <%end%>        
        </tr>
      <% end %>
    </tbody>
  </table>
</div>
<%= will_paginate @informe %>
  <%if @report.reportlines.size > 0%>
    <table class="draggable sortable table table-striped table-bordered table-condensed">
      <thead>
        <tr>
              <th>Registro</th>
              <th>Valor</th>
        </tr>
      </thead>
      <tbody>
        <!--This will be sent when the report has some sumarize lines-->
        <%@report.reportlines.each do |linea|%>
          <tr>
            <%tabla = eval(linea.modulo.camelize.singularize + ".all")%>
            <td><%=linea.modulo.humanize%></td>
            <td><%=tabla.size%></td>
          </tr>
        <%end%>
      </tbody>
    </table>
  <%end%>

app/views/reports/index.html.erb
<h1>Reports</h1>
<table class="table table-striped table-bordered table-condensed">
  <thead>
    <tr>
      <th>ID</th>
      <th>Nombre</th>
      <th>Created at</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @reports.each do |report| %>
      <tr>
        <td><%= report.id %></td>
        <td><%= link_to report.nombre, report_path(report) %></td>
        <td><%= report.created_at %></td>
        <td>
          <%= link_to 'Edit', edit_report_path(report), :class => 'btn btn-mini' %>
          <%= link_to 'Destroy', report_path(report), :method => :delete, :confirm => 'Are you sure?', :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'New', new_report_path, :class => 'btn btn-primary' %>

app/views/reports/new.html.erb
<%= render :partial => 'form' %>

app/views/reports/show.html.erb
<%=render :partial=>"shared/breadcrumbs", :locals=>{:model_name=>request.path_parameters[:controller],:model_id=>@report.id, :parent_model=>nil}%>
<h1>Report</h1>

<p>
  <b>Nombre</b><br>
  <%= @report.nombre %>
</p>

<p>
  <b>Descripcion</b><br>
  <%= @report.descripcion %>
</p>

<p>
  <b>Modulo</b><br>
  <%= @report.table %>
</p>

<p>
  <b>Registros Por Pagina</b><br>
  <%= @report.por_pagina %>
</p>

<b>Columnas Seleccionadas</b><br>
<ol>
  <% if not @report.column_names == nil%>
    <% @report.column_names.each do |column| %>
      <li><%= column %></li>
    <% end %>  
  <% end %>      
</ol>

<b>Parametros</b><br>
<ol>
  <% for reportparam in @report.reportparams %>
  <li><%= h reportparam.fieldname %> <%= h reportparam.filter %> <%= h reportparam.fieldvalue %></li>
  <% end %>
</ol>

<b>Ordenar Por</b><br>
<ol>
  <% for reportsortby in @report.reportsortbies %>
  <li><%= h reportsortby.fieldname %> <%= reportsortby.orden %></li>
  <% end %>
</ol>

<b>Lineas Personalizadas</b><br>
<ol>
  <% for reportline in @report.reportlines %>
  <li><%= h reportline.modulo %></li>
  <% end %>
</ol>
<div class="form-actions">
  <%= link_to 'Back', reports_path, :class => 'btn'  %>
  <%= link_to 'Edit', edit_report_path(@report), :class => 'btn' %>
  <%= link_to 'Delete', report_path(@report), :method => 'delete', :confirm => 'Are you sure?', :class => 'btn btn-danger' %>
</div>

app/views/reports/update_column_names.html.erb
<% if @columns.present? %>
	jojo
<% end %>